print('The Input comand in Python is like the Read function in Fortran, it allows the user make real time inputs into the source code as it runs')
print( 'Example\nPlease input an interger value:')
x=input()
print( 'PLease input a second integer value:')
y=input()
print ('x and y have been defined as', x, type(x), y, type(y))
print ("x+y=",int(x)+int(y))
print ('while, xy,is', x+y) 

print('')
print('To condense the number of code lines we can write the above as')
a=int(input('Please insert integer number'))
b=int(float(input("Please insert a number")))
c=float(input('Please insert a fractional number'))
print('a+b+c =', a+b+c, type(a+b+c))
